server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.138.128:3306/yeb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: Sdh512!@#
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认60000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 0
      # 连接超时时间，默认30000
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  redis:
    host: 192.168.33.10
    port: 6379
    password: 6585962sdh
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  rabbitmq:
    username: admin
    password: 6585962sdh
    host: 59.110.138.128
    port: 5672
    # 消息确认回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true

mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名
  type-aliases-package: com.cdh.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
# Mybatis SQL日志输出  打印方法接口所在的包
logging:
  level:
    com.cdh.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密的密钥
  secret: yeb-secret
  # JWT的超时时间
  expiration: 604800
  tokenHead: Bearer
